### ISSUE TITLE
Implementation of PARALLEL

### ISSUE THREAD

**Issue by hhr114** [snap-stanford/distance-encoding#7]
Hi, 
I am very appreciate your work. I have trouble performing DEGNN on OGBn-arXiv as the slow serial implementation. And the "--parallel" setting now can;t work.
Would you please fix the implementation of PARALLEL?

**Comment by Abel0828** [comment]
Hi there! Thanks for following up our work and for your reaching out. 

There are two reasons that we did not use --parallel: 1. The Python kernel has some internal problems supporting multiprocessing. That causes the program to crash sometimes when dealing with a very large dataset with huge number of spawning tasks. 2. We did not see significant speedup even when the parallel mode works, which may likely due to the overhead for python to handle the job pool.  If you want to experiment on a very large dataset, I suggest that you test with partial data by setting `--data_usage` at this point. We are still working to solve the problem.

**Comment by hhr114** [comment]
Thanks so much for your response.
